### ISSUE TITLE
Error when using a different sfreq

### ISSUE THREAD

**Issue by FarnoodF** [nbara/python-meegkit#16]
I try to run the following class instance:

```python
from meegkit import asr

asr.ASR(sfreq=64)
```

but it gives me the following error:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-264-fafe23240154> in <module>
      1 from meegkit import asr
      2 
----> 3 asr.ASR(sfreq=64)

c:\~\python\python38\lib\site-packages\meegkit\asr.py in __init__(self, sfreq, cutoff, blocksize, win_len, win_overlap, max_dropout_fraction, min_clean_fraction, name, method, **kwargs)
    124             80.0, (sfreq / 2.0) - 1.0), sfreq / 2.0]) * 2.0 / sfreq
    125         M = np.array([3, 0.75, 0.33, 0.33, 1, 1, 3, 3])
--> 126         B, A = yulewalk(8, F, M)
    127         self.ab_ = (A, B)
    128         self.cov_ = []

c:\~\python\python38\lib\site-packages\meegkit\utils\asr.py in yulewalk(order, F, M)
    241             inc = (j - nb) / (ne - nb)
    242 
--> 243         Ht[0][nb:ne + 1] = np.array(inc * M[i + 1] + (1 - inc) * M[i])
    244         nb = ne + 1
    245 

ValueError: could not broadcast input array from shape (385) into shape (257)
```

**Comment by nbara** [comment]
Hi @FarnoodF, 

If you look at the code, the default yulewalk filter breakpoints are located at the following frequencies:

`[0, 2, 3, 13, 16, 40, np.min((80, sfreq / 2 - 1)), sfreq / 2])`.

So `sfreq=64` is too low and is not going to work here. This ASR code was only tested at slightly higher sampling frequencies.

Does the Matlab implementation run at sfreq = 64 hz ?

**Comment by FarnoodF** [comment]
Hi! Thanks for the answer.
That's what I though too, but I ran the code in Matlab and it works fine for 64Hz.
In Matlab you get a yulwalk error only below 34Hz.

**Comment by nbara** [comment]
I just tested this code (from https://github.com/s4rify/rASRMatlab/blob/master/rASRToolbox/asr_calibrate.m#L118) in Matlab and it fails for me:

```matlab
sfreq=64;
F = [0, 2, 3, 13, 16, 40, min(80.0, (sfreq / 2.0) - 1.0), sfreq / 2.0] * 2.0 / sfreq;
M = [3, 0.75, 0.33, 0.33, 1, 1, 3, 3];
[B, A] = yulewalk(8, F, M);
>> Error using yulewalk (line 106)
>> Frequencies must be non-decreasing.
```

**Comment by nbara** [comment]
That said, the filter step is not that critical. You can just remove all breakpoints above 64hz in the filter design (`F` and `M`) and I guess it will work fine.

**Comment by FarnoodF** [comment]
Nice! Thanks for the help.
