### ISSUE TITLE
Information about filter bank analysis (FBA) and task-related component analysis (TRCA)

### ISSUE THREAD

**Issue by gferraro2019** [nbara/python-meegkit#26]
Hi,

I am currently working in a human factors research team to implement an SSVEP-based BCI of high-speed visual evoked potentials.

We are already using your library for part of our pipeline such as RESS, but we would like to test the approach explained in this document as well:

"An SSVEP-based high-speed BCI using dry EEG electrodes"
https://www.nature.com/articles/s41598-018-32283-8

In short, they show how it is possible to overcome the CCA algorithm by using a filter bank analysis (FBA) as part of preprocessing and the activity-related component analysis (TRCA) as a classification algorithm for the target classes.

Does Python-meegkit include or do you intend to include the FBA or TRCA algorithms?

Thank you.

**Comment by nbara** [comment]
Hi @gferraro2019, no I'm afraid this toolbox does not include FBA + TRCA, and I hadn't really planned to implement this technique, as I am not working with SSVEP myself at the moment.

However, looking at the paper TRCA seems very easy to implement, and I would be happy to accept and help with any PR if you want to give it a shot.

**Comment by gferraro2019** [comment]
Ok, I would like to try.

Thanks.

**Comment by gferraro2019** [comment]
Hello,

I have translated the @mnakanishi (author's paper) Matlab tutorial in Python and I got the same results if you want I can push this to your repo.

Also. for the moment I'm not going to spend other time on that.

Please let me know what do you think about it.

Regards.

**Comment by nbara** [comment]
Sure, you can open an PR and push your code, I'll try to find some time to integrate it in the codebase in the coming weeks
