### ISSUE TITLE
Projecting RESS components on new observatios of data

### ISSUE THREAD

**Issue by Hororohoruru** [nbara/python-meegkit#27]
Hello!

We have been using this package's RESS implementation in our recent work with SSVEPs and it has been a great help, thank you for that!

I wanted to ask a question regarding the 'maps' object being output from RESS (refered to as 'mixing matrix' in the docstring) and what they have diferent from the pure eigenvectors coming out from the linear eigendecomposition. We would be interested to know whether it is feasible to compute RESS on a set of observations and the use the maps (or eigenvectors) to transform a new observation into the same space of those outputed by the function. For example:

- An array of shape (4000, 32, 40) is inputed to the RESS function keeping just the first component, thus obtaining an output of shape (4000, 1, 40)

- I have a new example of shape (4000, 32) that I want to convert to the RESS component space (4000, 1) using the same components computed from the first transformation. How should I do this?

Thank you very much.

**Comment by nbara** [comment]
Hi @Hororohoruru,

(This is just a quick answer and I haven't had time to test it myself)

Bad news and good news: 
- you can't do what you want to do "out of the box" in MEEGkit; the `maps` object allows you to get from RESS space to sensor space;
- what you want to to is relatively straightforward, and will only have to modify the following `ress.py` code slightly: 
https://github.com/nbara/python-meegkit/blob/aed858dc3603a3b71e620df3f29da6ae1a8f68da/meegkit/ress.py#L98

You just want to also output `V`, like so:
```python
    # reconstruct RESS component time series
    out = np.zeros((n_samples, n_keep, n_trials))
    for t in range(n_trials):
        out[..., t] = X[:, :, t] @ V[:, np.arange(n_keep)]

    return out, maps, V
```        
        
Then, to view your 'new example' `x` in RESS space you should be able to do:

```python
>>> x.shape 
(4000, 32) 
>>> x @ V[:, np.arange(n_keep)
```

Let me know if that helps.

**Comment by Hororohoruru** [comment]
Thank you very much! We will try proceeding like that.

Would you be interested in adding this as a feature? I can make a quick PR. Otherwise we will keep it modified for internal use

**Comment by nbara** [comment]
Yes that would be great, thanks!
