### ISSUE TITLE
Bug in detrending of epoched data

### ISSUE THREAD

**Issue by OleBialas** [nbara/python-meegkit#40]
There seems to be a bug in the detrending function. When i use it on two raw (two dimensional) data, the result is as expected but when I use it on epoched data, the result is very strange - probably there is an issue with reshaping the matrix, see my example below:

```
import numpy
from matplotlib import pyplot as plt
from meegkit.detrend import detrend

time = numpy.arange(0, 10, 0.01)

# on raw data the detrending works as expected:
X = numpy.zeros([len(time), 3])
X[:, 0], X[:, 1], X[:, 2] = numpy.sin(time)+5, numpy.sin(time), numpy.sin(time)-5

X += numpy.random.randn(X.shape[0], X.shape[1])

fix, ax = plt.subplots(2)
for x in X.T:
    ax[0].plot(time, x)
X, _, _ = detrend(X, 1)
for x in X.T:
    ax[1].plot(time, x)

# but on epoched data the result looks strange:
X = numpy.zeros([len(time), 3, 100])
X[:, 0] = numpy.repeat(numpy.sin(time)[:, numpy.newaxis], 100, axis=1)+5
X[:, 1] = numpy.repeat(numpy.sin(time)[:, numpy.newaxis], 100, axis=1)
X[:, 2] = numpy.repeat(numpy.sin(time)[:, numpy.newaxis], 100, axis=1)-5
X += numpy.random.randn(X.shape[0], X.shape[1], X.shape[2])

fix, ax = plt.subplots(2)
for x in X.mean(axis=2).T:
    ax[0].plot(time, x)
X, _, _ = detrend(X, 1)
for x in X.mean(axis=2).T:
    ax[1].plot(time, x)


```

**Comment by nbara** [comment]
@OleBialas Hi, thanks for letting me know ! I've never really used the technique on epoched data. I will look into it in the next days.

**Comment by nbara** [comment]
I've been thinking about this issue, and I wonder what the correct behaviour should be for epoched data. 

I don't think the detrending function **should** handle 3D data, unless the epochs are assumed to be consecutive (which the current code already handles well I think)

The most straightforward solution in your case is to handle each epoch separately, but that's equivalent to calling detrend on each epoch in a loop. 

What I should do is add a warning to the docstring such as `Warning: if 3D data are provided, epochs are assumed to be consecutive`

**Comment by OleBialas** [comment]
I think you are right, I came to the conclusion that, in my case, there is not much of a point in using detrend on the epochs anyways so I just went with using it on the raw data.
