### ISSUE TITLE
IndexError with asr.fit() for a [100s-150s] window and sfreq=500 Hz

### ISSUE THREAD

**Issue by A-Fermo** [nbara/python-meegkit#44]
Hi,

Thank you for this great library! I am facing a weird problem while trying to use asr.fit(). Following your ASR example, below is the code I want to run:

```
start_window = 100 
end_window = 150
sfreq = 500
asr = ASR(sfreq=sfreq,method='riemann')
train_idx = np.arange(start_window * sfreq, end_window * sfreq, dtype=int)
_, sample_mask = asr.fit(EEG_filt_data[:, train_idx])
```
But I get the following error:
```
  File ".../EEG_preprocessing.py", line 367, in <module>
    _, sample_mask = asr.fit(EEG_filt_data[:, train_idx])

  File ".../anaconda3/envs/mne/lib/python3.8/site-packages/meegkit/asr.py", line 173, in fit
    clean, sample_mask = clean_windows(

  File ".../anaconda3/envs/mne/lib/python3.8/site-packages/meegkit/asr.py", line 393, in clean_windows
    clean = np.delete(X, sample_mask2remove, 1)

  File "<__array_function__ internals>", line 5, in delete

  File ".../anaconda3/envs/mne/lib/python3.8/site-packages/numpy/lib/function_base.py", line 4480, in delete
    keep[obj,] = False

IndexError: arrays used as indices must be of integer (or boolean) type
```

It seems that the problem occurs only in the following situation (I don't know why): 
- `clean window` of`50s` length;
- `start_window` fixed at `100`;
- `sfreq` fixed at `500`. 

Indeed when I change one variable while keeping fixed the others (giving for instance `50`, `100` and `499`) it works fine. Maybe it is due to some kind of multiple relationship?

Versions used:
`numpy = 1.20.1`
`mne = 0.22.1`

Thank you!

**Comment by nbara** [comment]
Hi @A-Fermo, I can't reproduce this error. If it's not too large, would it be possible to share your `EEG_filt_data[:, train_idx]` matrix ? 

You can use `np.save()`  and drag and drop the file directly here. If you're not comfortable sharing the link publicly you can also email it to me (nicolas dot barascud at gmail )

**Comment by A-Fermo** [comment]
Hi @nbara, thank you for your reply. Sure! I've attached the file (12.8 MB). If, for some reason, you need further information about my original EEG data, I could definitely email them to you. 

[EEG_filt_data.zip](https://github.com/nbara/python-meegkit/files/6591257/EEG_filt_data.zip)

Also sorry it was the version of `meegkit` (0.1.1) that I wanted to indicate.

**Comment by nbara** [comment]
How odd, I can't reproduce this error using your data....

![tty](https://user-images.githubusercontent.com/10333715/120640274-903a7c80-c472-11eb-8e29-ad080fa2f5a7.gif)

Can you try updating your numpy version perhaps ?

**Comment by nbara** [comment]
Also, can you try to inspect the contents of the `sample_mask2remove` array in asr.py:

https://github.com/nbara/python-meegkit/blob/f2fe945acf16b7698b0efa8b8c062afbd65ffb75/meegkit/asr.py#L384

Here's what I get:

<img width="513" alt="Screenshot 2021-06-03 at 13 55 23" src="https://user-images.githubusercontent.com/10333715/120640999-6766b700-c473-11eb-8df1-4b508e448634.png">

**Comment by nbara** [comment]
Finally, also triple check that you are using the most recent commit from meegkit : 

If you cloned the repo locally:

```
git fetch --all; git pull
pip install -e .
```

or if you used a direct install via pip's git+https : 

```bash
pip install git+https://github.com/nbara/python-meegkit.git@master#egg=meegkit
```

**Comment by A-Fermo** [comment]
After updating numpy it changed nothing (it is maybe because I am using conda). However you've made me double check my code and the problem was indeed due to a bad referencing -- you were right! I had first referenced to the average but eventually changed for the mastoids (because of some connectivity measures I need to perform). While doing the change I made a stupid typo... my bad!

Still I don't understand why you couldn't reproduce the error with my own data and why it worked with all other combinations of values for window length, start_window and sfreq...

But anyway now, with a correct referencing to the mastoids, it does work perfectly. Thank you very much and sorry again for that!

Best regards

**Comment by A-Fermo** [comment]
Sorry, I just realised a small conflict between the latest versions of `scikit-learn` and `pyriemann`. 

While running `asr = ASR(sfreq=500,method='euclid',estimator='lwf')` you mentioned above I get the following error:
```
File ".../EEG_preprocessing.py", line 374, in <module>
    Y[:, i, :] = asr.transform(X[:, i, :])
File ".../anaconda3/envs/mne/lib/python3.8/site-packages/meegkit/asr.py", line 233, in transform
    cov = pyriemann.estimation.covariances(X_filt[None, ...],
AttributeError: 'NoneType' object has no attribute 'estimation'
```
It is because when trying to import `pyriemann`, python returns the following error:
```
import pyriemann
Traceback (most recent call last):
File "<ipython-input-2-9084d25c8e35>", line 1, in <module>
    import pyriemann
File "/home/aurelien/anaconda3/envs/mne/lib/python3.8/site-packages/pyriemann/__init__.py", line 6, in <module>
    from . import clustering
File "/home/aurelien/anaconda3/envs/mne/lib/python3.8/site-packages/pyriemann/clustering.py", line 5, in <module>
    from sklearn.cluster._kmeans import _init_centroids
ImportError: cannot import name '_init_centroids' from 'sklearn.cluster._kmeans' (/home/aurelien/anaconda3/envs/mne/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py)
```

This issue occurs with the latest version of `scikit-learn` (0.24.2) and has been raised [here](https://github.com/pyRiemann/pyRiemann/issues/108). To fix this, `pyriemann` needs to be (re-)install with the `setup.py` file directly from the source repository. For now it won't work if installed from pypi as it is commonly suggested.

Sorry again,

Best.

**Comment by nbara** [comment]
Actually my requirements.txt should already force you to install pyriemann from github, instead of the pipy which conflicts with sklearn: 

https://github.com/nbara/python-meegkit/blob/f2fe945acf16b7698b0efa8b8c062afbd65ffb75/requirements.txt#L15

**Comment by A-Fermo** [comment]
Oh that's right! So the problem occurs only when we have `pyriemann` already installed (from pypi) beforehand. Thank you again. 
Best.
