### ISSUE TITLE
pypi installer

### ISSUE THREAD

**Issue by lokinou** [nbara/python-meegkit#45]
Hello, I really like your implementation of Artifact Subspace Rejection and I would like to import it in my own package.
I however cannot use your package as a requirement in PyPI because it doest not allow git install.

Would you be kind enought to upload  to PyPI the dist from the current version that seems to nicely build?

**Comment by nbara** [comment]
Hi @lokinou 

I plan to release meegkit to pypi eventually but there are a couple things I want to do first (mostly removing untested code).

In the meantime, can you not install via git+https in your requirements.txt, like so?

```
meegkit @ git+https://github.com/nbara/python-meegkit

```

**Comment by lokinou** [comment]
Hello, it does not work.

I must add a mention in readme or in notebooks to install it manually via
your commands.
No link allowed in the externals.
Thanks for asking


Nicolas Barascud ***@***.***> schrieb am Fr., 15. Okt. 2021,
16:03:

**Comment by nbara** [comment]
I've had a look at your repo. I think I know why it doesn't work. I'll open an issue there.
