### ISSUE TITLE
Question on dss_line() usage

### ISSUE THREAD

**Issue by adswa** [nbara/python-meegkit#47]
Hi, its awesome that there is an implementation of the ZAPline algorithm in Python! I'm trying to use it, but I somehow fail to remove the noise components with it. I'm convinced that I must be doing something obvious wrong - any idea what it may be?

I'm using Elekta MEG data (322 MEG channels, after Signal Space Separation) that show an artifact at 60Hz stemming from a presentation display. 
Here is its PSD:
![psd022](https://user-images.githubusercontent.com/29738718/137493826-dfe71772-3ad9-442b-811c-49b5241f9df3.png)

Here's the code I am running:

```
>>> import mne
>>> from meegkit.dss import dss_line
# read in the data with mne-python
>>> raw_fname = Path(datadir) / f'sub-{subject}/meg' / f'sub-{subject}_task-memento_proc-sss_meg.fif'
>>> raw = mne.io.read_raw_fif(raw_fname)
>>> raw.load_data()
>>> data, artifact = dss_line(raw._data.T, fline=60, sfreq=1000)
Power of components removed by DSS: 0.00
```

Putting the data back into the MNE Raw Object and visualizing the psd plot shows an almost identical profile, with the 60Hz component being pretty much unaffected.
![after_dss](https://user-images.githubusercontent.com/29738718/137494568-b7375fda-d2b9-420c-998c-02e7e40bc678.png)

Any idea what I might be doing wrong here? 
Thanks much in advance!

**Comment by nbara** [comment]
Hi @adswa ! Yeah clearly something is wrong here.

Have you tried increasing the number of components to remove `nremove` to see if it changes anything? I haven't really had time to test zapline with MEG data (especially a combination of grad+mag). 

What are those huge peaks around 300 hz ? Those are no 60hz harmonics.

If that doesn't work, I'd be interested to have a look at the data myself (if you don't mind sharing a file, or a part of it).

**Comment by adswa** [comment]
Oh, wow... I should have checked :facepalm:  - thanks so much for taking a look and helping out, really appreciated!
