### ISSUE TITLE
Memory usage of `dss_line()`

### ISSUE THREAD

**Issue by eort** [nbara/python-meegkit#56]
Hi, 

I came across this repository when I was looking for an implementation of ZAPline. Really nice that you took the effort to translate the original matlab package. I have played around with it on my data, and for most of it, it works really nicely. 

However, one thing that worries me a bit, is the memory usage of the `dss_line()`. So far, I tried to run it on MEG data (300 channels x 1.8x10^6 samples), but there was no chance that my laptop (24GB) could offer enough memory for `dss_line` to finish. Only if I cropped the data considerably it worked.

Of course, eventually the scripts will run on an HPC, so memory shouldn't be a big problem there, still it is quite annoying that I can't run and check those scripts locally before exporting them to the hpc. So I was wondering whether there are some magic tricks that I can do to lower the memory footprint? Settings that I have missed or something?  I tried to trace the memory consumption of the function (where I was sufficiently confident to not affect functionality), and could indeed reduce the usage here and there, but the peak is still higher than what my pc can handle.

If helpful, I can provide more information of any kind.

**Comment by nbara** [comment]
Hi @eort 

You are 100% right and this is something that I've identified already (see #50 ). One obvious thing to try is to compute the covariance by blocks. I'll try to get around to it soon (but if you want to open a PR sooner you're welcome 😉 )

**Comment by eort** [comment]
Ah great! Well, I doubt I can produce a reasonable PR, but I shall try to further look into what parts of the code are particularly memory-hungry. Thanks!

**Comment by nbara** [comment]
In that case I'll leave the PR open until you have had enough time to test it, ok?

**Comment by eort** [comment]
Sure! While testing it is already quite clear that the slowest part of the process (so far) are the ffts in gaussfilter: 
https://github.com/nbara/python-meegkit/blob/7f8192a74215ad91108ab59a16dc19a8fc7e687f/meegkit/utils/sig.py#L348-L354

**Comment by nbara** [comment]
Yes I came to the same conclusion. I have to do some FFTing here to compute the bias covariance, but at least now it's done over hopefully smaller matrices so it should not hog your memory as much 🤞

**Comment by eort** [comment]
Not sure it really did save memory though. I just managed to edit the code here and there to save memory, and it did finish finally! (Beautiful Psds afterwards!). Tomorrow I shall have a somewhat more systematic look which of my edits actually did save memory, and compose a PR of them. Then you can decide what of it you want to keep and what not :smile:

**Comment by nbara** [comment]
Sounds good

**Comment by eort** [comment]
quick question. Does it make more sense to start the PR based on #57, or based on master?

**Comment by nbara** [comment]
you can base it on #57

**Comment by nbara** [comment]
Closed via #57 (for now)

**Comment by nbara** [comment]
Thanks @eort !
