### ISSUE TITLE
Dataset format, can you clarify it?

### ISSUE THREAD

**Issue by Ildaron** [nbara/python-meegkit#65]
Hello, can you clarify about dataset format?  for example_asr.py

My dataset has the next structure  in txt or excel formats and put this data to numpy 
ch1 ch2 ch3 ch4 ch5 ch6 ch7 ch8
1    1      1      1    1     1    1     1    

But when I use example for ASR and put this data in numpy to Raw  (line - 17 in example_asr.py)- I receive error

**Comment by nbara** [comment]
Can you do `data.shape` and give me the output?

**Comment by Ildaron** [comment]
Hi @nbara  thank you for your answer,   
 - shape (8, 7120), the example of dataset - https://github.com/HackerBCI/EEGwithRaspberryPI/blob/master/dataset/2.Blinking_Chewing%20Raw_Data.txt

**Comment by Ildaron** [comment]
Hi @nbara thank you for your answer, is it the correct format, that I use?
in the line- 
`_, sample_mask = asr.fit(raw[:, train_idx])`  from example_asr.py 

I receive the next error 
IndexError: index 8 is out of bounds for axis 1 with size 8

**Comment by Ildaron** [comment]
Hi @nbara do you have any update?

**Comment by nbara** [comment]
hi @Ildaron, can you do `print(raw.shape)` ? 

It looks like you have the wrong dimensions. It should be `channels * time`

**Comment by Ildaron** [comment]
@nbara thank you for your reply, Yes I also think that problem with the dimension, can you just share some dataset that was used for your library?  Then I quickly will figure out what was wrong

**Comment by nbara** [comment]
@Ildaron An example dataset is shown in https://github.com/nbara/python-meegkit/blob/master/examples/example_asr.py which should be runnable on your machine once you have cloned the repo

**Comment by Ildaron** [comment]
@nbara thank you so much
