### ISSUE TITLE
Questions about TSPCA

### ISSUE THREAD

**Issue by JD-Zhu** [nbara/python-meegkit#70]
Hi @nbara ,

Thanks for this cool package.

We have some MEG data recorded from a KIT system (160 channels of data + 3 reference channels) and would like to try using your TSPCA implementation for reducing environmental noise in the data. We perform our analyses in MNE so it's nice to be able to do this in python. @larsoner

I just had a couple of questions: 1) In the README document, it says that "TSCPA may give inaccurate results due to insufficient testing (contributions welcome!)" I was wondering if there had been any updates about this? 2) Are there any recommended parameters when using the meegkit.tspca.tsr() function (e.g. for the shifts and weights)?

Thank you very much!

**Comment by nbara** [comment]
Have you had a look at what is available in MNE for sensor noise suppression? 

I'm thinking of https://mne.tools/stable/auto_tutorials/preprocessing/60_maxwell_filtering_sss.html in particular, which seems to be super well documented and tested

**Comment by JD-Zhu** [comment]
> Have you had a look at what is available in MNE for sensor noise suppression?
> 
> I'm thinking of https://mne.tools/stable/auto_tutorials/preprocessing/60_maxwell_filtering_sss.html in particular, which seems to be super well documented and tested

Thanks a lot @nbara !

We would like to try both this and TSPCA if possible - would be nice to make use of the reference channel data. Would you recommend just calling the meegkit.tspca.tsr() function with the default parameters? And for testing purpose, what would be some ways to assess whether the TSPCA is working well?

**Comment by JD-Zhu** [comment]
Thanks @larsoner. We have done a rough comparison of the tsPCA results from MEG160 (the acquisition software for KIT system) and meegkit, and the results seemed quite similar!

**Comment by nbara** [comment]
> Would you recommend just calling the meegkit.tspca.tsr() function with the default parameters?

Yes I would definitely start with that. But I don't really have additional recommendations beyond what is given in the original paper, TSCPA is definitely the method I used the least myself in the toolbox... 

Maybe experiment with it on a known dataset that uses the same MEG scanner, to check that the results look as they should and that you did not remove any useful information. 

Keep me posted if you experience bugs in my code, I'll look into it 👍

**Comment by JD-Zhu** [comment]
Thanks @nbara !
