### ISSUE TITLE
Issue with Removing Line Noise in MEG Data Using dss_line_iter

### ISSUE THREAD

**Issue by colehank** [nbara/python-meegkit#79]
Hi everyone,

I used the dss_line_iter function to remove line noise from EEG and MEG data. The process works well on EEG but little strange on MEG. 

Here is the function I use for removing line noise from MNE raw objects:

```
def linenoise_clean(raw, fline):
    # raw : mne.raw
    data = raw.get_data().T 
    data = np.expand_dims(data, axis=2) # make mne.raw dss_line_iter readable 
    sfreq = raw.info['sfreq']

    out, _ = dss.dss_line_iter(data, fline, sfreq,nfft=400,n_iter_max=100)
    cleaned_raw = mne.io.RawArray(out.T.squeeze(), raw.info)# array2mne.raw
    
    return cleaned_raw
```

For EEG, this method effectively eliminates the line noise, as shown in the PSD plot of raw EEG(above) and cleaned EEG(below).
![EEG](https://github.com/user-attachments/assets/413eaa3e-4a00-4a66-b6d0-8592c2a33e95)

However, when applying the same function to MEG data, the results are quite unusual. The line noise in the 0-300 Hz range remains consistent with the original data, and there’s an emergence of new line noise above 300 Hz, which was not present in the original data. ![output](https://github.com/user-attachments/assets/e5c96a0f-425e-424a-b86e-300faabc8630)

Has anyone else encountered this issue when applying dss_line_iter to MEG data? Any insights or suggestions on how to tweak the parameters or use an alternative approach to address this anomaly would be greatly appreciated.

Thank you in advance for your help and suggestions!

**Comment by nbara** [comment]
Hi @colehank , does `dss_line()` produce the same result? Have you tried increasing the number of components to remove (might be > 1 for MEG data)

**Comment by colehank** [comment]
Thanks for your replying, I tried `dss_line` nremove from 1 to 3, the results is the same as `dss_line_iter` , here's my code: 

```auto
from meegkit import dss
import mne
import numpy as np

root = 'MEG/MEG-BIDS'
raw = mne.io.read_raw_ctf(f'{root}/sub-01/ses-CoCo01/meg/sub-01_ses-CoCo01_task-CoCo_run-01_meg.ds')


def zapline_denoise(raw,nremove,fline=50,plot=True):
    data  = raw.get_data().T
    data  = np.expand_dims(data, axis=2)  # (nsample, nchan, ntrial(1))
    sfreq = raw.info['sfreq']
    
    out, _ = dss.dss_line(data, fline, sfreq, nremove=nremove)
    cleaned_raw = mne.io.RawArray(out.T.squeeze(),raw.info)
    if plot:
        cleaned_raw.plot_psd(n_jobs=-1)
    
    return cleaned_raw
   
   cleaned_raw.plot_psd()
```

```auto
Output: Power of components removed by DSS: 0.00
```

![](./assets/No-811-image.png)

**Comment by colehank** [comment]
Thank you for your reply. I tried using `dss_line` with nremove values from 1 to 3, and the results seemed identical to those obtained with `dss_line_iter`. Here is the code I used:
```auto
from meegkit import dss
import mne
import numpy as np

def zapline_denoise(raw,nremove,fline=50):
    data  = raw.get_data().T
    data  = np.expand_dims(data, axis=2)  # (nsample, nchan, ntrial(1))
    sfreq = raw.info['sfreq']
    
    out, _ = dss.dss_line(data, fline, sfreq, nremove=nremove)
    cleaned_raw = mne.io.RawArray(out.T.squeeze(),raw.info)

    return cleaned_raw

root = 'MEG/MEG-BIDS'
raw = mne.io.read_raw_ctf(f'{root}/sub-01/ses-CoCo01/meg/sub-01_ses-CoCo01_task-CoCo_run-01_meg.ds')
cleaned_raw = zapline_denoise(raw,nremove = 3)
cleaned_raw.plot_psd()
```

```auto
Output: Power of components removed by DSS: 0.00
```

![output](https://github.com/user-attachments/assets/bad4c371-2f3f-479d-83e0-ecbbee5a665b)

**Comment by nbara** [comment]
Can you upload some data so I can take a look ?

**Comment by colehank** [comment]
Here is my [cropped MEG](https://drive.google.com/file/d/1qXjgJ8CbRYri37K3pJk3mt-u_IKpM4_C/view?usp=sharing).

**Comment by colehank** [comment]
Oh I completely missed selecting the mag channel. Thanks so much for your patience. (btw, It's a really nice toolkit! )

**Comment by colehank** [comment]
Sorry to bother you again, but I have one more question: Why did the y-axis of the PSD plot shift from the original ±40 to a range between 260 and 340 after cleaning?

**Comment by nbara** [comment]
Oh, isn't it because of the shenanigans I am using with the units? Haven't checked but you'd probably need to input the data in T not fT to `raw._data` after cleaning
