### ISSUE TITLE
Applying ZapLine to continuous data

### ISSUE THREAD

**Issue by marcpabst** [nbara/python-meegkit#8]
Hi, thanks for your package.

I was wondering if you suggest segmenting continuous data before applying the ZapLine algorithm. I tried to use it on a rather large chunk of data and it failed while trying to allocate an array of 32.2 TiB. 

One option I can think of would be to cut my data into arbitrary segments of a few seconds each, apply ZapLine, and then piece the segments back together. What do you think?

**Comment by marcpabst** [comment]
Sorry, I supplied the data in the form `n_channels x n_samples`, not `n_samples x n_channels`.

For `nremove = 1` it works well, but `nremove > 1` always fails:

    ValueError: Weights should be the same n_times as X.

I was able to reproduce this error using random data:

    data = np.random.rand(300,4)
    denoised_data, artifacts = meegkit.dss.dss_line(data, 50., sfreq, nremove=2)

Any ideas why?

**Comment by nbara** [comment]
Hi @marcpabst, 

Regarding your first message, happy you got it sorted. Let me know if the issue comes back in the future, as there is an easy improvement that could be done, which is to compute the covariances by blocks instead of doing it all in one go. 

Thanks for reporting into that `n_remove > 1` bug, I will try to look into it this week.

**Comment by nbara** [comment]
@marcpabst could you please check branch [`nb/fix-issue-8`](https://github.com/nbara/python-meegkit/tree/nb/fix-issue-8) and see if it fixes your problem?

**Comment by marcpabst** [comment]
Thanks for your quick response! The fixed branch seems to work fine. I will report back when I had to test it in more detail.

**Comment by marcpabst** [comment]
I think it works now fine, although I can't compare it to the original MATLAB implementation atm. Thanks!
